FROM bde2020/spark-worker:2.4.0-hadoop2.7

MAINTAINER Iuliia Gavrilenko <yulya952@rambler.ru>

ENV SPARK_WORKER_WEBUI_PORT 8081
ENV SPARK_WORKER_LOG /spark/logs
ENV SPARK_MASTER "spark://spark-master:7077"

EXPOSE 8081